version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
  polynomial-app:
    container_name: polynomial-app
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
